// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdX6MUXHGCJj8EOkKrrFl9i6KoxJcrevA',
    appId: '1:35641233724:web:2d630e7af49a227ec94e39',
    messagingSenderId: '35641233724',
    projectId: 'tadaapp-f298d',
    authDomain: 'tadaapp-f298d.firebaseapp.com',
    storageBucket: 'tadaapp-f298d.appspot.com',
    measurementId: 'G-38JEKT9Z18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6qczqksK1OZFsSr09eYE9h5TYpjryLWk',
    appId: '1:35641233724:android:9477b0ac45db1fdcc94e39',
    messagingSenderId: '35641233724',
    projectId: 'tadaapp-f298d',
    storageBucket: 'tadaapp-f298d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUdUhtgESX5Zt7dSYpqVjrbUYqoRigNuw',
    appId: '1:35641233724:ios:63d3c49d1a1f06a7c94e39',
    messagingSenderId: '35641233724',
    projectId: 'tadaapp-f298d',
    storageBucket: 'tadaapp-f298d.appspot.com',
    iosBundleId: 'com.example.tada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUdUhtgESX5Zt7dSYpqVjrbUYqoRigNuw',
    appId: '1:35641233724:ios:e8995b8942aab942c94e39',
    messagingSenderId: '35641233724',
    projectId: 'tadaapp-f298d',
    storageBucket: 'tadaapp-f298d.appspot.com',
    iosBundleId: 'com.example.tada.RunnerTests',
  );
}
